[ERROR 2020-11-29 20:16:05,569] function_runner.py: 254  Runner Thread raised error.
Traceback (most recent call last):
  File "/home/mi-lab02/.local/lib/python3.6/site-packages/ray/tune/function_runner.py", line 248, in run
    self._entrypoint()
  File "/home/mi-lab02/.local/lib/python3.6/site-packages/ray/tune/function_runner.py", line 316, in entrypoint
    self._status_reporter.get_checkpoint())
  File "/home/mi-lab02/.local/lib/python3.6/site-packages/ray/tune/function_runner.py", line 575, in _trainable_func
    output = fn()
  File "rnn_main_tune.py", line 274, in train_main
    neptune=neptune)
  File "rnn_main_tune.py", line 154, in train
    optimizer = eval(mystring)(net.parameters(), lr=args.lr)
  File "<string>", line 1, in <module>
NameError: name 'optim' is not defined
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/mi-lab02/.local/lib/python3.6/site-packages/ray/tune/function_runner.py", line 267, in run
    raise e
  File "/home/mi-lab02/.local/lib/python3.6/site-packages/ray/tune/function_runner.py", line 248, in run
    self._entrypoint()
  File "/home/mi-lab02/.local/lib/python3.6/site-packages/ray/tune/function_runner.py", line 316, in entrypoint
    self._status_reporter.get_checkpoint())
  File "/home/mi-lab02/.local/lib/python3.6/site-packages/ray/tune/function_runner.py", line 575, in _trainable_func
    output = fn()
  File "rnn_main_tune.py", line 274, in train_main
    neptune=neptune)
  File "rnn_main_tune.py", line 154, in train
    optimizer = eval(mystring)(net.parameters(), lr=args.lr)
  File "<string>", line 1, in <module>
NameError: name 'optim' is not defined

