Failure # 1 (occurred at 2020-11-29_20-35-30)
Traceback (most recent call last):
  File "/home/mi-lab02/.local/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 726, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/home/mi-lab02/.local/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 489, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "/home/mi-lab02/.local/lib/python3.6/site-packages/ray/worker.py", line 1454, in get
    raise value
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.

