[ERROR 2020-11-29 20:12:06,435] function_runner.py: 254  Runner Thread raised error.
Traceback (most recent call last):
  File "/home/mi-lab02/.local/lib/python3.6/site-packages/ray/tune/function_runner.py", line 248, in run
    self._entrypoint()
  File "/home/mi-lab02/.local/lib/python3.6/site-packages/ray/tune/function_runner.py", line 316, in entrypoint
    self._status_reporter.get_checkpoint())
  File "/home/mi-lab02/.local/lib/python3.6/site-packages/ray/tune/function_runner.py", line 575, in _trainable_func
    output = fn()
  File "rnn_main_tune.py", line 258, in train_main
    dim_output=args.dim_out).to(device)
  File "/home/mi-lab02/rnn_classifier/rnn_model.py", line 12, in __init__
    self.fc1 = nn.Linear(self.dim_hidden1, self.dim_hidden2)
  File "/home/mi-lab02/.local/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 76, in __init__
    self.weight = Parameter(torch.Tensor(out_features, in_features))
TypeError: new() received an invalid combination of arguments - got (float, int), but expected one of:
 * (*, torch.device device)
      didn't match because some of the arguments have invalid types: (!float!, !int!)
 * (torch.Storage storage)
 * (Tensor other)
 * (tuple of ints size, *, torch.device device)
 * (object data, *, torch.device device)

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/mi-lab02/.local/lib/python3.6/site-packages/ray/tune/function_runner.py", line 267, in run
    raise e
  File "/home/mi-lab02/.local/lib/python3.6/site-packages/ray/tune/function_runner.py", line 248, in run
    self._entrypoint()
  File "/home/mi-lab02/.local/lib/python3.6/site-packages/ray/tune/function_runner.py", line 316, in entrypoint
    self._status_reporter.get_checkpoint())
  File "/home/mi-lab02/.local/lib/python3.6/site-packages/ray/tune/function_runner.py", line 575, in _trainable_func
    output = fn()
  File "rnn_main_tune.py", line 258, in train_main
    dim_output=args.dim_out).to(device)
  File "/home/mi-lab02/rnn_classifier/rnn_model.py", line 12, in __init__
    self.fc1 = nn.Linear(self.dim_hidden1, self.dim_hidden2)
  File "/home/mi-lab02/.local/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 76, in __init__
    self.weight = Parameter(torch.Tensor(out_features, in_features))
TypeError: new() received an invalid combination of arguments - got (float, int), but expected one of:
 * (*, torch.device device)
      didn't match because some of the arguments have invalid types: (!float!, !int!)
 * (torch.Storage storage)
 * (Tensor other)
 * (tuple of ints size, *, torch.device device)
 * (object data, *, torch.device device)


